$(document).ready(function(){
	//Tab栏 
	$("#tablan_shouye").on("click",function(){
		window.location="index.html";
	})
	$("#tablan_remai").on("click",function(){
	window.location="sales.html";
	})
	$("#tablan_zhuanti").on("click",function(){
	 	window.location="subject.html";
	})
	$("#tablan_wode").on("click",function(){
		window.location='mine.html';
	})
})	